### ISSUE TITLE
Question: Post append Stylespans

### ISSUE THREAD

**Issue by liz3** [FXMisc/RichTextFX#715]
Hey there, i have another question.
But first: RichTextFX is a awesome Library and its amazing what you can do with it!

Im my Program, i am doing highlighting the same way as the JavaKeyWord Demo: https://github.com/FXMisc/RichTextFX/blob/master/richtextfx-demos/src/main/java/org/fxmisc/richtext/demo/JavaKeywords.java

Now my question, i want afterwards to add a background color to a line. And i only have the line Number.
I tried to get the spans with `GenericStyleArea#getStyleSpans(int paragraph)` and then append it with the `StyleSpans#append` method, sadly this did not work at all, after i saw that the `append` method is returning the spans, i tried to re set these spans to the paragraph in the area, sadly also didnt work(infact there was a case where i ran into a stackoverflow Exception).

So my question: What is the proper way to add style to a specific line with style spans.
(If i missed the point in the Documentation which explains that, i would be very happy if you could provide me with a link to it).

Regards
Liz3

**Comment by JordanMartinez** [comment]
I'm having some difficulty in understanding what you're trying to do. 

It sounds like, somewhere in the method where you compute the `StyleSpans` for highlighting, that you would like to overlay another style on top of a section in the `StyleSpans` object. Is that correct? In other words, you're not trying to append a style to the end of the `StyleSpans` object, so that it now is longer than before. You're trying to do something like the following, which would imply `overlay`, correct?
````java
text \n text text text text \n text text text
| ----- computed highlighting ---- |
       | background color  | // also add a background color "on top of" the regular styles
````

Which subclass of `GenericStyledArea` are you using?

**Comment by liz3** [comment]
yes, sorry infact i am trying to set a layer ontop of the highlighting.
But its a different css selector.
I am using CodeArea.

**Comment by JordanMartinez** [comment]
> But its a different css selector.

Could you explain that more?

**Comment by liz3** [comment]
so in the JavaKeyWordExample you map the Matcher result to a css selector which than sets: `-fx-fill`, i am doing the same, but when i am afterwards trying to set the background color im using a different selector, it was just as information

**Comment by JordanMartinez** [comment]
Ok. So, is this issue closed then?

**Comment by liz3** [comment]
Could you maybe provide me a example usage of `StyleSpans#overlay` ?
Or is there some docs how to use this function?
Otherwise yes the question in answered.

Kind Regards,
Liz3

**Comment by JordanMartinez** [comment]
Looking at the type definition:
````java
public class StyleSpans<S> {
    /**
     * Applies the given bifunction {@code f} to this object's {@link StyleSpan} objects and
     * {@code that} {@link StyleSpan} objects and stores the result in the returned {@link StyleSpans} object.
     */
    default StyleSpans<S> overlay(StyleSpans<S> that, BiFunction<? super S, ? super S, ? extends S> f) {
    /* rest of code */
    }
````
you would do something like this:
````java
// if my style object was a list of Strings
StyleSpans<List<String>> spans = // creation code
List<String> styleToGoOnTop = Arrays.asList("one", "two", "three");
spans = spans.overlay(styleToGoOnTop, (bottomSpan, styleToGoOnTop0) -> {
    bottomSpan.addAll(styleToGoOnTop0);
    return bottomSpan;
}

**Comment by liz3** [comment]
<img width="697" alt="screenshot_333" src="https://user-images.githubusercontent.com/21298625/38123447-54bd6620-33db-11e8-85ba-86985f8f3bab.png">
The whole function: 

    public static StyleSpans<Collection<String>> merge(@Nullable StyleSpans<Collection<String>> 
      spans) {
        if (spans != null) {
            List<String> styleToGoOnTop = Collections.singletonList("marked");
            spans = spans.overlay(styleToGoOnTop, (bottomSpan, styleToGoOnTop0) -> {
                bottomSpan.addAll(styleToGoOnTop0);
                return bottomSpan;
            });
                }

        return spans;
    }

What am i doing wrong?

**Comment by JordanMartinez** [comment]
Oh, whoops! The method expects a `StyleSpans` object before the `BiFunction`. So, you could try this instead (you'll need a value for `offset`, `styleLength` and `fullLength` though):
````java
    public static StyleSpans<Collection<String>> merge(@Nullable StyleSpans<Collection<String>> 
      spans) {
        if (spans != null) {
            StyleSpansBuilder<Collection<String>> builder = new StyleSpansBuilder();
            builder.add(Collections.emptyList(), offset);
            builder.add(Collections.singletonList("marked"), styleLength);
            builder.add(Collections.emptyList(), fullLength - offset - styleLength);
            StyleSpans<Collection<String>> spansToGoOnTop = builder.create();
            spans = spans.overlay(spansToGoOnTop, (bottomSpan, list) -> {
                bottomSpan.addAll(list);
                return bottomSpan;
            });
                }

        return spans;
    }
````

**Comment by liz3** [comment]
Okay so i tried this, note i dont need a `offset` and `styleLength` since im trying to apply the spans onto the whole line, as mentioned before i just have the line number, so im using `area.paragraphs[NEEDED_LINE]` to get the thext length.
Sadly i get a `java.lang.UnsupportedOperationException` on the line `bottomSpan.addAll(list);`

Here the function:

    public static StyleSpans<Collection<String>> merge(@Nullable StyleSpans<Collection<String>>
                                                               spans, int lineLength) {
        if (spans != null) {
            StyleSpansBuilder<Collection<String>> builder = new StyleSpansBuilder();
            builder.add(Collections.emptyList(), 0);
            builder.add(Collections.singletonList("marked"), lineLength);
            builder.add(Collections.emptyList(), 0);
            StyleSpans<Collection<String>> spansToGoOnTop = builder.create();
            spans = spans.overlay(spansToGoOnTop, (bottomSpan, list) -> {
                bottomSpan.addAll(list);
                return bottomSpan;
            });
        }

        return spans;
      }
The whole Stacktrace:

`Exception in thread "JavaFX Application Thread" [30.3.2018 06:00:20 | ERROR] java.lang.UnsupportedOperationException
[30.3.2018 06:00:20 | ERROR] 	at java.util.AbstractCollection.add(AbstractCollection.java:262)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.utils.StyleSpanMerger.lambda$merge$0(StyleSpanMerger.java:23)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.model.StyleSpansBuilder.overlay(StyleSpansBuilder.java:87)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.model.StyleSpans.overlay(StyleSpans.java:190)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.utils.StyleSpanMerger.merge(StyleSpanMerger.java:22)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.core.code.highlighting.Highlighting.mapMarked(Highlighting.kt:150)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.core.code.highlighting.Highlighting.access$mapMarked(Highlighting.kt:11)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.core.code.highlighting.Highlighting$sub$1.accept(Highlighting.kt:18)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.core.code.highlighting.Highlighting$sub$1.accept(Highlighting.kt:11)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.FilterStream.lambda$observeInputs$0(FilterStream.java:20)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.QueuingStreamNotifications.lambda$head$0(NotificationAccumulator.java:217)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.SuspendableBase.resume(SuspendableBase.java:64)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.MultiGuard.close(Guard.java:83)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.Suspendable$1.resumeSource(Suspendable.java:118)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.Suspendable$1.suspendSource(Suspendable.java:104)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.EventStreams$3.lambda$observeInputs$0(EventStreams.java:105)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.value.ValBase.invalidate(ValBase.java:32)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.SuspendableBoolean.release(SuspendableBoolean.java:24)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.Suspendable.suspendWhile(Suspendable.java:49)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.update(GenericEditableStyledDocumentBase.java:228)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.Tuple3.exec(Tuple3.java:43)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.setStyleSpans(GenericEditableStyledDocumentBase.java:174)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.model.SimpleEditableStyledDocument.setStyleSpans(SimpleEditableStyledDocument.java:10)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.GenericStyledArea.setStyleSpans(GenericStyledArea.java:1098)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.core.code.highlighting.Highlighting$sub$1.accept(Highlighting.kt:17)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.core.code.highlighting.Highlighting$sub$1.accept(Highlighting.kt:11)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.FilterStream.lambda$observeInputs$0(FilterStream.java:20)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.QueuingStreamNotifications.lambda$head$0(NotificationAccumulator.java:217)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.SuspendableBase.resume(SuspendableBase.java:64)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.MultiGuard.close(Guard.java:83)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.Suspendable$1.resumeSource(Suspendable.java:118)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.Suspendable$1.suspendSource(Suspendable.java:104)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.NonAccumulativeStreamNotifications.lambda$head$0(NotificationAccumulator.java:134)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ProperEventStream.emit(ProperEventStream.java:18)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.EventStreams$3.lambda$observeInputs$0(EventStreams.java:105)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.value.ChangeListenerWrapper.accept(Val.java:786)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.AbstractReducingStreamNotifications.lambda$head$0(NotificationAccumulator.java:248)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:68)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.ObservableBase.notifyObservers(ObservableBase.java:57)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.value.ValBase.invalidate(ValBase.java:32)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.SuspendableBoolean.release(SuspendableBoolean.java:24)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.CloseableOnceGuard.close(Guard.java:49)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.Suspendable.suspendWhile(Suspendable.java:49)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.update(GenericEditableStyledDocumentBase.java:228)
[30.3.2018 06:00:20 | ERROR] 	at org.reactfx.util.Tuple3.exec(Tuple3.java:43)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.model.GenericEditableStyledDocumentBase.replace(GenericEditableStyledDocumentBase.java:135)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.model.SimpleEditableStyledDocument.replace(SimpleEditableStyledDocument.java:10)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.GenericStyledArea.replace(GenericStyledArea.java:1147)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.GenericStyledArea.replaceText(GenericStyledArea.java:1134)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.EditActions.insertText(EditActions.java:32)
[30.3.2018 06:00:20 | ERROR] 	at org.fxmisc.richtext.EditActions.appendText(EditActions.java:15)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.core.code.CodeManager.setup(CodeManager.kt:70)
[30.3.2018 06:00:20 | ERROR] 	at com.skide.gui.project.ProjectGuiEventListeners$setupNewTabForDisplay$1.run(ProjectGui.kt:194)
[30.3.2018 06:00:20 | ERROR] 	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
[30.3.2018 06:00:20 | ERROR] 	at java.security.AccessController.doPrivileged(Native Method)
[30.3.2018 06:00:20 | ERROR] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
[30.3.2018 06:00:20 | ERROR] 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
[30.3.2018 06:00:20 | ERROR] 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
[30.3.2018 06:00:20 | ERROR] 	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
[30.3.2018 06:00:20 | ERROR] 	at java.lang.Thread.run(Thread.java:748)`

JDK: 1.0.8_162

**Comment by JordanMartinez** [comment]
(for future reference, posting your stack trace in the above manner makes it very hard to read. I'm not sure whether that's the fault of your console not printing it better or something else. Each `[Time stamp | Error] at class(file.java:lineNumber)` should be on its own line.)

> java.lang.UnsupportedOperationException on the line bottomSpan.addAll(list);

`bottomSpan` is probably a list wrapped in a `Collections.unmodifiableList` call. So, if you create a new list like so, it should fix that:
````java
List<Collection<String>> l = new ArrayList(bottomSpan.size() + list.size());
l.addAll(bottomSpan);
l.addAll(other);
return l;
````

**Comment by liz3** [comment]
Hey, im very thankful for you help and im sorry i have to annoy you with this, but i would really like to get it work!
Sadly it still does not apply the changes, so im giving you every details i can, that may explain what im doing wrong.

Here the method that is applying the changes as we talked before:

  
    public static StyleSpans<Collection<String>> merge(@Nullable StyleSpans<Collection<String>>
                                                               spans, int lineLength) {
        if (spans != null) {
            StyleSpansBuilder<Collection<String>> builder = new StyleSpansBuilder();
            builder.add(Collections.emptyList(), 0);
            builder.add(Collections.singletonList("marked"), lineLength);
            builder.add(Collections.emptyList(), 0);
            StyleSpans<Collection<String>> spansToGoOnTop = builder.create();
            spans = spans.overlay(spansToGoOnTop, (bottomSpan, list) -> {
                List<String> l = new ArrayList<>(bottomSpan.size() + list.size());
                l.addAll(bottomSpan);
                l.addAll(list);
                return l;
            });
        }

        return spans;
    }
Here the usage, dont be suprised its Kotlin, but should not be a problem:

    fun mapMarked() {

        //manager.marked is a set of line-numbers
        for (line in manager.marked) {

            //is invoked from another thread so Platform.runLater is required
            Platform.runLater {
                //get the lines text
                val text = area.paragraphs[line].text
                //Currently 0 would be changed to absolute line start later
                val start = 0
                val end = start + text.length
                //get the spans
                val spans = area.getStyleSpans(start, end)
                //The merge method we talked about before
                val result = StyleSpanMerger.merge(spans, end)
                //reset the style
                area.setStyleSpans(start, end, result)
            }

        }

    }
And here the CSS Selector, i am trying to overlay:

    .styled-text-area .text.marked {

    -rtfx-background-color: rgba(218, 120, 70, 0.3);

    }

Can you maybe help me solving that?
Again thank you for all the help until now!

Regards,
Liz3

**Comment by JordanMartinez** [comment]
The following worked for me. Note: I'm using `InlineCssTextArea`, but if you use the same `merge` method I described above for `Collection<String>`, then it should still work:
````java
import javafx.application.Platform;
import org.fxmisc.richtext.InlineCssTextAreaAppTest;
import org.fxmisc.richtext.model.StyleSpans;
import org.junit.Test;

public class LizHelp extends InlineCssTextAreaAppTest {

    @Test
    public void dostuff() {
        interact(() -> {
            area.replaceText("paragraph 0\nparagraph 1\nparagraph 2");
            area.setStyle(0, area.getLength(),"-rtfx-background-color: red;");
        });
        sleep(2000);
        Platform.runLater(() -> {
            int paragraphIndex = 1;
            int lineLength = area.getParagraphLength(paragraphIndex);
            StyleSpans<String> spans = area.getStyleSpans(paragraphIndex);
            StyleSpans<String> updated = spans.overlay(
                    StyleSpans.singleton("-fx-fill: white;", lineLength),
                    (original, added) -> original + added);
            area.setStyleSpans(paragraphIndex, 0, updated);
        });
        sleep(2000);
    }
}
````

**Comment by JordanMartinez** [comment]
Also, you can add Java syntax highlighting to your code blocks if you follow [these steps](https://help.github.com/articles/creating-and-highlighting-code-blocks/). (Kotlin is probably supported) It makes reading it a bit easier.

**Comment by liz3** [comment]
Thank you so so so much!!!!!!!!!!!!!!
In the end it turned out, the reason why it was not working is that the `area.setStyleSpans(paragraphIndex, 0, updated);` is triggering the `area.richChanges().filter({ ch -> ch.inserted != ch.removed })` which was resetting the Highlighting instantly.

So i just added a validation that the method which invokes the merge got called and now it works!!! Thank you very much

**Comment by JordanMartinez** [comment]
Ah... yes, you should be using `area.plainChanges().filter(x -> !x.isIdentity())` so that it ignores any style (e.g. syntax highlighting) changes.

**Comment by JordanMartinez** [comment]
Hmm... I started to update the demo to use that and now I'm getting a recursive update like what you described. I'd guess that #695 has potentially introduced a regression.
